//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySnooper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserClan {
            get {
                return ((string)(this["UserClan"]));
            }
            set {
                this["UserClan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerAddress {
            get {
                return ((string)(this["ServerAddress"]));
            }
            set {
                this["ServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int UserCountry {
            get {
                return ((int)(this["UserCountry"]));
            }
            set {
                this["UserCountry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F0FFFF|13|0|0|0|0|Tahoma")]
        public string ChannelMessage {
            get {
                return ((string)(this["ChannelMessage"]));
            }
            set {
                this["ChannelMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("808000|12|0|0|0|0|Tahoma")]
        public string JoinMessage {
            get {
                return ((string)(this["JoinMessage"]));
            }
            set {
                this["JoinMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("808000|12|0|0|0|0|Tahoma")]
        public string PartMessage {
            get {
                return ((string)(this["PartMessage"]));
            }
            set {
                this["PartMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("808000|12|0|0|0|0|Tahoma")]
        public string QuitMessage {
            get {
                return ((string)(this["QuitMessage"]));
            }
            set {
                this["QuitMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FF0000|13|0|0|0|0|Tahoma")]
        public string OfflineMessage {
            get {
                return ((string)(this["OfflineMessage"]));
            }
            set {
                this["OfflineMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FFFF00|13|0|0|0|0|Tahoma")]
        public string ActionMessage {
            get {
                return ((string)(this["ActionMessage"]));
            }
            set {
                this["ActionMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E9967A|13|0|0|0|0|Tahoma")]
        public string UserMessage {
            get {
                return ((string)(this["UserMessage"]));
            }
            set {
                this["UserMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FF0000|13|0|0|0|0|Tahoma")]
        public string NoticeMessage {
            get {
                return ((string)(this["NoticeMessage"]));
            }
            set {
                this["NoticeMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADFF2F|13|0|0|0|0|Tahoma")]
        public string BuddyJoinedMessage {
            get {
                return ((string)(this["BuddyJoinedMessage"]));
            }
            set {
                this["BuddyJoinedMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BuddyList {
            get {
                return ((string)(this["BuddyList"]));
            }
            set {
                this["BuddyList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BanList {
            get {
                return ((string)(this["BanList"]));
            }
            set {
                this["BanList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds\\pmbeep.wav")]
        public string PMBeep {
            get {
                return ((string)(this["PMBeep"]));
            }
            set {
                this["PMBeep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds\\pmbeep.wav")]
        public string HBeep {
            get {
                return ((string)(this["HBeep"]));
            }
            set {
                this["HBeep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds\\buddyjoined.wav")]
        public string BJBeep {
            get {
                return ((string)(this["BJBeep"]));
            }
            set {
                this["BJBeep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PMBeepEnabled {
            get {
                return ((bool)(this["PMBeepEnabled"]));
            }
            set {
                this["PMBeepEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HBeepEnabled {
            get {
                return ((bool)(this["HBeepEnabled"]));
            }
            set {
                this["HBeepEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BJBeepEnabled {
            get {
                return ((bool)(this["BJBeepEnabled"]));
            }
            set {
                this["BJBeepEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MessageJoinedGame {
            get {
                return ((bool)(this["MessageJoinedGame"]));
            }
            set {
                this["MessageJoinedGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HostGameName {
            get {
                return ((string)(this["HostGameName"]));
            }
            set {
                this["HostGameName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HostUseWormnat {
            get {
                return ((bool)(this["HostUseWormnat"]));
            }
            set {
                this["HostUseWormnat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HostInfoToChannel {
            get {
                return ((bool)(this["HostInfoToChannel"]));
            }
            set {
                this["HostInfoToChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WaExe {
            get {
                return ((string)(this["WaExe"]));
            }
            set {
                this["WaExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I am playing!")]
        public string AwayText {
            get {
                return ((string)(this["AwayText"]));
            }
            set {
                this["AwayText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MarkAway {
            get {
                return ((bool)(this["MarkAway"]));
            }
            set {
                this["MarkAway"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I am back!")]
        public string BackText {
            get {
                return ((string)(this["BackText"]));
            }
            set {
                this["BackText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SendBack {
            get {
                return ((bool)(this["SendBack"]));
            }
            set {
                this["SendBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MessageTime {
            get {
                return ((bool)(this["MessageTime"]));
            }
            set {
                this["MessageTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D3D3D3|12|0|0|0|0|Tahoma")]
        public string MessageTimeStyle {
            get {
                return ((string)(this["MessageTimeStyle"]));
            }
            set {
                this["MessageTimeStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00FFFF|13|0|0|0|1|Tahoma")]
        public string HyperLinkStyle {
            get {
                return ((string)(this["HyperLinkStyle"]));
            }
            set {
                this["HyperLinkStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WAExeAsked {
            get {
                return ((bool)(this["WAExeAsked"]));
            }
            set {
                this["WAExeAsked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("simple")]
        public string LoginType {
            get {
                return ((string)(this["LoginType"]));
            }
            set {
                this["LoginType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TusNick {
            get {
                return ((string)(this["TusNick"]));
            }
            set {
                this["TusNick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TusPass {
            get {
                return ((string)(this["TusPass"]));
            }
            set {
                this["TusPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoLogIn {
            get {
                return ((bool)(this["AutoLogIn"]));
            }
            set {
                this["AutoLogIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowLoginScreen {
            get {
                return ((bool)(this["ShowLoginScreen"]));
            }
            set {
                this["ShowLoginScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADFF2F|13|0|0|0|0|Tahoma")]
        public string LeagueFoundMessage {
            get {
                return ((string)(this["LeagueFoundMessage"]));
            }
            set {
                this["LeagueFoundMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds\\LeagueFound.wav")]
        public string LeagueFoundBeep {
            get {
                return ((string)(this["LeagueFoundBeep"]));
            }
            set {
                this["LeagueFoundBeep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeagueFoundBeepEnabled {
            get {
                return ((bool)(this["LeagueFoundBeepEnabled"]));
            }
            set {
                this["LeagueFoundBeepEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds\\LeagueFail.wav")]
        public string LeagueFailBeep {
            get {
                return ((string)(this["LeagueFailBeep"]));
            }
            set {
                this["LeagueFailBeep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeagueFailBeepEnabled {
            get {
                return ((bool)(this["LeagueFailBeepEnabled"]));
            }
            set {
                this["LeagueFailBeepEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoJoinAnythingGoes {
            get {
                return ((bool)(this["AutoJoinAnythingGoes"]));
            }
            set {
                this["AutoJoinAnythingGoes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AwayMessage {
            get {
                return ((string)(this["AwayMessage"]));
            }
            set {
                this["AwayMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsUpgraded {
            get {
                return ((bool)(this["SettingsUpgraded"]));
            }
            set {
                this["SettingsUpgraded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int UserRank {
            get {
                return ((int)(this["UserRank"]));
            }
            set {
                this["UserRank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchForThese {
            get {
                return ((string)(this["SearchForThese"]));
            }
            set {
                this["SearchForThese"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NewsSeen {
            get {
                return ((string)(this["NewsSeen"]));
            }
            set {
                this["NewsSeen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimeLogsDeleted {
            get {
                return ((string)(this["TimeLogsDeleted"]));
            }
            set {
                this["TimeLogsDeleted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteLogs {
            get {
                return ((bool)(this["DeleteLogs"]));
            }
            set {
                this["DeleteLogs"] = value;
            }
        }
    }
}
