//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySnooper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserClan {
            get {
                return ((string)(this["UserClan"]));
            }
            set {
                this["UserClan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wormnet1.team17.com")]
        public string ServerAddress {
            get {
                return ((string)(this["ServerAddress"]));
            }
            set {
                this["ServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int UserCountry {
            get {
                return ((int)(this["UserCountry"]));
            }
            set {
                this["UserCountry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F0FFFF|13|0|0|0|0|Tahoma")]
        public string ChannelMessageStyle {
            get {
                return ((string)(this["ChannelMessageStyle"]));
            }
            set {
                this["ChannelMessageStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("808000|12|0|0|0|0|Tahoma")]
        public string JoinMessageStyle {
            get {
                return ((string)(this["JoinMessageStyle"]));
            }
            set {
                this["JoinMessageStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("808000|12|0|0|0|0|Tahoma")]
        public string PartMessageStyle {
            get {
                return ((string)(this["PartMessageStyle"]));
            }
            set {
                this["PartMessageStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("808000|12|0|0|0|0|Tahoma")]
        public string QuitMessageStyle {
            get {
                return ((string)(this["QuitMessageStyle"]));
            }
            set {
                this["QuitMessageStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FF0000|13|0|0|0|0|Tahoma")]
        public string OfflineMessageStyle {
            get {
                return ((string)(this["OfflineMessageStyle"]));
            }
            set {
                this["OfflineMessageStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FFFF00|13|0|0|0|0|Tahoma")]
        public string ActionMessageStyle {
            get {
                return ((string)(this["ActionMessageStyle"]));
            }
            set {
                this["ActionMessageStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E9967A|13|0|0|0|0|Tahoma")]
        public string UserMessageStyle {
            get {
                return ((string)(this["UserMessageStyle"]));
            }
            set {
                this["UserMessageStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FF0000|13|0|0|0|0|Tahoma")]
        public string NoticeMessageStyle {
            get {
                return ((string)(this["NoticeMessageStyle"]));
            }
            set {
                this["NoticeMessageStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BuddyList {
            get {
                return ((string)(this["BuddyList"]));
            }
            set {
                this["BuddyList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BanList {
            get {
                return ((string)(this["BanList"]));
            }
            set {
                this["BanList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds\\pmbeep.wav")]
        public string PMBeep {
            get {
                return ((string)(this["PMBeep"]));
            }
            set {
                this["PMBeep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds\\pmbeep.wav")]
        public string HBeep {
            get {
                return ((string)(this["HBeep"]));
            }
            set {
                this["HBeep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds\\buddyjoined.wav")]
        public string BJBeep {
            get {
                return ((string)(this["BJBeep"]));
            }
            set {
                this["BJBeep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PMBeepEnabled {
            get {
                return ((bool)(this["PMBeepEnabled"]));
            }
            set {
                this["PMBeepEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HBeepEnabled {
            get {
                return ((bool)(this["HBeepEnabled"]));
            }
            set {
                this["HBeepEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BJBeepEnabled {
            get {
                return ((bool)(this["BJBeepEnabled"]));
            }
            set {
                this["BJBeepEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MessageJoinedGame {
            get {
                return ((bool)(this["MessageJoinedGame"]));
            }
            set {
                this["MessageJoinedGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HostGameName {
            get {
                return ((string)(this["HostGameName"]));
            }
            set {
                this["HostGameName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HostUseWormnat {
            get {
                return ((bool)(this["HostUseWormnat"]));
            }
            set {
                this["HostUseWormnat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HostInfoToChannel {
            get {
                return ((bool)(this["HostInfoToChannel"]));
            }
            set {
                this["HostInfoToChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WaExe {
            get {
                return ((string)(this["WaExe"]));
            }
            set {
                this["WaExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I am playing!")]
        public string AwayText {
            get {
                return ((string)(this["AwayText"]));
            }
            set {
                this["AwayText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MarkAway {
            get {
                return ((bool)(this["MarkAway"]));
            }
            set {
                this["MarkAway"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I am back!")]
        public string BackText {
            get {
                return ((string)(this["BackText"]));
            }
            set {
                this["BackText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SendBack {
            get {
                return ((bool)(this["SendBack"]));
            }
            set {
                this["SendBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MessageTime {
            get {
                return ((bool)(this["MessageTime"]));
            }
            set {
                this["MessageTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D3D3D3|12|0|0|0|0|Tahoma")]
        public string MessageTimeStyle {
            get {
                return ((string)(this["MessageTimeStyle"]));
            }
            set {
                this["MessageTimeStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00FFFF|13|0|0|0|1|Tahoma")]
        public string HyperLinkStyle {
            get {
                return ((string)(this["HyperLinkStyle"]));
            }
            set {
                this["HyperLinkStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WAExeAsked {
            get {
                return ((bool)(this["WAExeAsked"]));
            }
            set {
                this["WAExeAsked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("simple")]
        public string LoginType {
            get {
                return ((string)(this["LoginType"]));
            }
            set {
                this["LoginType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TusNick {
            get {
                return ((string)(this["TusNick"]));
            }
            set {
                this["TusNick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TusPass {
            get {
                return ((string)(this["TusPass"]));
            }
            set {
                this["TusPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoLogIn {
            get {
                return ((bool)(this["AutoLogIn"]));
            }
            set {
                this["AutoLogIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADFF2F|13|0|0|0|0|Tahoma")]
        public string LeagueFoundMessageStyle {
            get {
                return ((string)(this["LeagueFoundMessageStyle"]));
            }
            set {
                this["LeagueFoundMessageStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds\\LeagueFound.wav")]
        public string LeagueFoundBeep {
            get {
                return ((string)(this["LeagueFoundBeep"]));
            }
            set {
                this["LeagueFoundBeep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeagueFoundBeepEnabled {
            get {
                return ((bool)(this["LeagueFoundBeepEnabled"]));
            }
            set {
                this["LeagueFoundBeepEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds\\LeagueFail.wav")]
        public string LeagueFailBeep {
            get {
                return ((string)(this["LeagueFailBeep"]));
            }
            set {
                this["LeagueFailBeep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeagueFailBeepEnabled {
            get {
                return ((bool)(this["LeagueFailBeepEnabled"]));
            }
            set {
                this["LeagueFailBeepEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AwayMessage {
            get {
                return ((string)(this["AwayMessage"]));
            }
            set {
                this["AwayMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsUpgraded {
            get {
                return ((bool)(this["SettingsUpgraded"]));
            }
            set {
                this["SettingsUpgraded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int UserRank {
            get {
                return ((int)(this["UserRank"]));
            }
            set {
                this["UserRank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchForThese {
            get {
                return ((string)(this["SearchForThese"]));
            }
            set {
                this["SearchForThese"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NewsSeen {
            get {
                return ((string)(this["NewsSeen"]));
            }
            set {
                this["NewsSeen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimeLogsDeleted {
            get {
                return ((string)(this["TimeLogsDeleted"]));
            }
            set {
                this["TimeLogsDeleted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteLogs {
            get {
                return ((bool)(this["DeleteLogs"]));
            }
            set {
                this["DeleteLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wormnet1.team17.com")]
        public string ServerAddresses {
            get {
                return ((string)(this["ServerAddresses"]));
            }
            set {
                this["ServerAddresses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowWormsChannel {
            get {
                return ((bool)(this["ShowWormsChannel"]));
            }
            set {
                this["ShowWormsChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ChangeWormsNick {
            get {
                return ((bool)(this["ChangeWormsNick"]));
            }
            set {
                this["ChangeWormsNick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WormsNick {
            get {
                return ((string)(this["WormsNick"]));
            }
            set {
                this["WormsNick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CloseToTray {
            get {
                return ((bool)(this["CloseToTray"]));
            }
            set {
                this["CloseToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QuitMessagee {
            get {
                return ((string)(this["QuitMessagee"]));
            }
            set {
                this["QuitMessagee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#AnythingGoes,")]
        public string AutoJoinChannels {
            get {
                return ((string)(this["AutoJoinChannels"]));
            }
            set {
                this["AutoJoinChannels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpammingChecked {
            get {
                return ((bool)(this["SpammingChecked"]));
            }
            set {
                this["SpammingChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBannedUsers {
            get {
                return ((bool)(this["ShowBannedUsers"]));
            }
            set {
                this["ShowBannedUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColumnOrder {
            get {
                return ((string)(this["ColumnOrder"]));
            }
            set {
                this["ColumnOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Notificator {
            get {
                return ((string)(this["Notificator"]));
            }
            set {
                this["Notificator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AskNotificatorOff {
            get {
                return ((bool)(this["AskNotificatorOff"]));
            }
            set {
                this["AskNotificatorOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AskLeagueSearcherOff {
            get {
                return ((bool)(this["AskLeagueSearcherOff"]));
            }
            set {
                this["AskLeagueSearcherOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sounds\\LeagueFound.wav")]
        public string NotificatorSound {
            get {
                return ((string)(this["NotificatorSound"]));
            }
            set {
                this["NotificatorSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NotificatorSoundEnabled {
            get {
                return ((bool)(this["NotificatorSoundEnabled"]));
            }
            set {
                this["NotificatorSoundEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WormsPassword {
            get {
                return ((string)(this["WormsPassword"]));
            }
            set {
                this["WormsPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TrayFlashing {
            get {
                return ((bool)(this["TrayFlashing"]));
            }
            set {
                this["TrayFlashing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TrayNotifications {
            get {
                return ((bool)(this["TrayNotifications"]));
            }
            set {
                this["TrayNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBannedMessages {
            get {
                return ((bool)(this["ShowBannedMessages"]));
            }
            set {
                this["ShowBannedMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int GameListGridRowStarts {
            get {
                return ((int)(this["GameListGridRowStarts"]));
            }
            set {
                this["GameListGridRowStarts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int RightColumnStars {
            get {
                return ((int)(this["RightColumnStars"]));
            }
            set {
                this["RightColumnStars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClientListDGColumns {
            get {
                return ((string)(this["ClientListDGColumns"]));
            }
            set {
                this["ClientListDGColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowInfoColumn {
            get {
                return ((bool)(this["ShowInfoColumn"]));
            }
            set {
                this["ShowInfoColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Volume {
            get {
                return ((int)(this["Volume"]));
            }
            set {
                this["Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChatMode {
            get {
                return ((bool)(this["ChatMode"]));
            }
            set {
                this["ChatMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ActionMessageWithGT {
            get {
                return ((bool)(this["ActionMessageWithGT"]));
            }
            set {
                this["ActionMessageWithGT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnergySaveMode {
            get {
                return ((bool)(this["EnergySaveMode"]));
            }
            set {
                this["EnergySaveMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MuteState {
            get {
                return ((bool)(this["MuteState"]));
            }
            set {
                this["MuteState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Buddies|9933CC00")]
        public string Group0 {
            get {
                return ((string)(this["Group0"]));
            }
            set {
                this["Group0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Group0List {
            get {
                return ((string)(this["Group0List"]));
            }
            set {
                this["Group0List"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Clanmates|8F07CEE6")]
        public string Group1 {
            get {
                return ((string)(this["Group1"]));
            }
            set {
                this["Group1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Group1List {
            get {
                return ((string)(this["Group1List"]));
            }
            set {
                this["Group1List"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("League players|AFFF8C00")]
        public string Group2 {
            get {
                return ((string)(this["Group2"]));
            }
            set {
                this["Group2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Group2List {
            get {
                return ((string)(this["Group2List"]));
            }
            set {
                this["Group2List"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Other 1|D7B024EB")]
        public string Group3 {
            get {
                return ((string)(this["Group3"]));
            }
            set {
                this["Group3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Group3List {
            get {
                return ((string)(this["Group3List"]));
            }
            set {
                this["Group3List"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Other 2|AFFF00FF")]
        public string Group4 {
            get {
                return ((string)(this["Group4"]));
            }
            set {
                this["Group4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Group4List {
            get {
                return ((string)(this["Group4List"]));
            }
            set {
                this["Group4List"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Other 3|D791A6BA")]
        public string Group5 {
            get {
                return ((string)(this["Group5"]));
            }
            set {
                this["Group5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Group5List {
            get {
                return ((string)(this["Group5List"]));
            }
            set {
                this["Group5List"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Other 4|B9D8BFD8")]
        public string Group6 {
            get {
                return ((string)(this["Group6"]));
            }
            set {
                this["Group6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Group6List {
            get {
                return ((string)(this["Group6List"]));
            }
            set {
                this["Group6List"] = value;
            }
        }
    }
}
