//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatSnooper.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreatSnooper.Localizations.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About WormNat 2: If you host with the game, then it will create the server on your computer and it will wait for players to join on a specified port (usually 17011). But most of the routers and firewall programs don&apos;t allow incoming connections, so nobody can join your game. You will need to enable port forwarding on your router and/or configure your firewall if you use one in order to let players join your game. WormNat2 uses a technique, that you can host games without incoming connections so your host wi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutWormNat2Text {
            get {
                return ResourceManager.GetString("AboutWormNat2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action message using &apos;&gt;&apos; character:.
        /// </summary>
        public static string ActionMessageGTText {
            get {
                return ResourceManager.GetString("ActionMessageGTText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action message style:.
        /// </summary>
        public static string ActionMessageStyleText {
            get {
                return ResourceManager.GetString("ActionMessageStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to ignore list.
        /// </summary>
        public static string AddIgnoreText {
            get {
                return ResourceManager.GetString("AddIgnoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to conversation.
        /// </summary>
        public static string AddToConvText {
            get {
                return ResourceManager.GetString("AddToConvText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new user to the list...
        /// </summary>
        public static string AddUserToList {
            get {
                return ResourceManager.GetString("AddUserToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask if I would like to turn off the league searcher when I host or join a game:.
        /// </summary>
        public static string AskLeagueSOffText {
            get {
                return ResourceManager.GetString("AskLeagueSOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask if I would like to turn off the notificator when I host or join a game:.
        /// </summary>
        public static string AskNotificatorOffText {
            get {
                return ResourceManager.GetString("AskNotificatorOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto join this channel.
        /// </summary>
        public static string AutoJoinText {
            get {
                return ResourceManager.GetString("AutoJoinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto login at startup:.
        /// </summary>
        public static string AutoLogInSettingText {
            get {
                return ResourceManager.GetString("AutoLogInSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto login:.
        /// </summary>
        public static string AutoLoginText {
            get {
                return ResourceManager.GetString("AutoLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set away.
        /// </summary>
        public static string AwayButtonAway {
            get {
                return ResourceManager.GetString("AwayButtonAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set back.
        /// </summary>
        public static string AwayButtonBack {
            get {
                return ResourceManager.GetString("AwayButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away text:.
        /// </summary>
        public static string AwayLabel {
            get {
                return ResourceManager.GetString("AwayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away Manager.
        /// </summary>
        public static string AwayManagerTitle {
            get {
                return ResourceManager.GetString("AwayManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away manager.
        /// </summary>
        public static string AwayManagerTooltip {
            get {
                return ResourceManager.GetString("AwayManagerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are away: {0}.
        /// </summary>
        public static string AwayManagerTooltipAway {
            get {
                return ResourceManager.GetString("AwayManagerTooltipAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is away: {0}.
        /// </summary>
        public static string AwayMessageFormat {
            get {
                return ResourceManager.GetString("AwayMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away message:.
        /// </summary>
        public static string AwayMessageText {
            get {
                return ResourceManager.GetString("AwayMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back message:.
        /// </summary>
        public static string BackMessageText {
            get {
                return ResourceManager.GetString("BackMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold:.
        /// </summary>
        public static string BoldLabel {
            get {
                return ResourceManager.GetString("BoldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseButtonContent {
            get {
                return ResourceManager.GetString("BrowseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string BuddiesGroupText {
            get {
                return ResourceManager.GetString("BuddiesGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ChangeButtonText {
            get {
                return ResourceManager.GetString("ChangeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set #worms nick to WormNet nick at startup:.
        /// </summary>
        public static string ChangeWormsNickText {
            get {
                return ResourceManager.GetString("ChangeWormsNickText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style of other users&apos; messages:.
        /// </summary>
        public static string ChannelMessageStyleText {
            get {
                return ResourceManager.GetString("ChannelMessageStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must join a channel first!.
        /// </summary>
        public static string ChannelOfflineText {
            get {
                return ResourceManager.GetString("ChannelOfflineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the scheme of the channel. Try to rejoin the channel!.
        /// </summary>
        public static string ChannelSchemeText {
            get {
                return ResourceManager.GetString("ChannelSchemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat mode on / off.
        /// </summary>
        public static string ChatModeTooltip {
            get {
                return ResourceManager.GetString("ChatModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with this user.
        /// </summary>
        public static string ChatText {
            get {
                return ResourceManager.GetString("ChatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your clan can contain only characters from the English alphabet and numbers..
        /// </summary>
        public static string ClanHasBadChar {
            get {
                return ResourceManager.GetString("ClanHasBadChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan.
        /// </summary>
        public static string ClanHeaderLabel {
            get {
                return ResourceManager.GetString("ClanHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. If you do not have clan you can leave this empty..
        /// </summary>
        public static string ClanInfoText {
            get {
                return ResourceManager.GetString("ClanInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clanmates.
        /// </summary>
        public static string ClanMatesGroupText {
            get {
                return ResourceManager.GetString("ClanMatesGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan:.
        /// </summary>
        public static string ClanText {
            get {
                return ResourceManager.GetString("ClanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseChatText {
            get {
                return ResourceManager.GetString("CloseChatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit button minimizes the snooper to tray:.
        /// </summary>
        public static string CloseToTrayText {
            get {
                return ResourceManager.GetString("CloseToTrayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the common settings! You won&apos;t be allowed to spam for league games (but you can still look for them). If this problem doesn&apos;t go away then the snooper may need to be updated..
        /// </summary>
        public static string CommonSettingFailText {
            get {
                return ResourceManager.GetString("CommonSettingFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string ConnectingText {
            get {
                return ResourceManager.GetString("ConnectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can contact me at http://www.tus-wa.com/profile/Tomi/ using private message.
        /// </summary>
        public static string ContactText {
            get {
                return ResourceManager.GetString("ContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has added {1} to the conversation..
        /// </summary>
        public static string ConversationAdded {
            get {
                return ResourceManager.GetString("ConversationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been removed from this conversation..
        /// </summary>
        public static string ConversationKick {
            get {
                return ResourceManager.GetString("ConversationKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has left the conversation..
        /// </summary>
        public static string ConversationLeave {
            get {
                return ResourceManager.GetString("ConversationLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has removed {1} from the conversation..
        /// </summary>
        public static string ConversationRemoved {
            get {
                return ResourceManager.GetString("ConversationRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C..
        /// </summary>
        public static string CountryHeaderLabel {
            get {
                return ResourceManager.GetString("CountryHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create game.
        /// </summary>
        public static string CreateGameText {
            get {
                return ResourceManager.GetString("CreateGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-GB.
        /// </summary>
        public static string CultureName {
            get {
                return ResourceManager.GetString("CultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DefaultText {
            get {
                return ResourceManager.GetString("DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete channel logs older than 30 days at startup:.
        /// </summary>
        public static string DeleteLogsText {
            get {
                return ResourceManager.GetString("DeleteLogsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This text cannot be empty!.
        /// </summary>
        public static string EmptyErrorMessage {
            get {
                return ResourceManager.GetString("EmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string EnabledText {
            get {
                return ResourceManager.GetString("EnabledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy save mode while playing:.
        /// </summary>
        public static string EnergySaveModeGameText {
            get {
                return ResourceManager.GetString("EnergySaveModeGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy save mode when snooper is hidden:.
        /// </summary>
        public static string EnergySaveModeWinText {
            get {
                return ResourceManager.GetString("EnergySaveModeWinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter this channel.
        /// </summary>
        public static string EnterChannelText {
            get {
                return ResourceManager.GetString("EnterChannelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text here...
        /// </summary>
        public static string EnterTextText {
            get {
                return ResourceManager.GetString("EnterTextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string ExampleLabel {
            get {
                return ResourceManager.GetString("ExampleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit snooper after hosting?.
        /// </summary>
        public static string ExitAfterHosting {
            get {
                return ResourceManager.GetString("ExitAfterHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitText {
            get {
                return ResourceManager.GetString("ExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter...
        /// </summary>
        public static string FilterText {
            get {
                return ResourceManager.GetString("FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Chooser.
        /// </summary>
        public static string FontChooserTitle {
            get {
                return ResourceManager.GetString("FontChooserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found text style:.
        /// </summary>
        public static string FoundStyleText {
            get {
                return ResourceManager.GetString("FoundStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game name:.
        /// </summary>
        public static string GameNameLabel {
            get {
                return ResourceManager.GetString("GameNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can contain only characters from the English alphabet!.
        /// </summary>
        public static string GamePassBadText {
            get {
                return ResourceManager.GetString("GamePassBadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string GamesText {
            get {
                return ResourceManager.GetString("GamesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General sounds.
        /// </summary>
        public static string GeneralSoundsText {
            get {
                return ResourceManager.GetString("GeneralSoundsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralText {
            get {
                return ResourceManager.GetString("GeneralText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} players.
        /// </summary>
        public static string GroupPlayersEditTitle {
            get {
                return ResourceManager.GetString("GroupPlayersEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A player from {0} comes online:.
        /// </summary>
        public static string GroupSoundSettingText {
            get {
                return ResourceManager.GetString("GroupSoundSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group sounds.
        /// </summary>
        public static string GroupSoundsText {
            get {
                return ResourceManager.GetString("GroupSoundsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string GroupText {
            get {
                return ResourceManager.GetString("GroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Snooper is used by {0} user(s)! {1}.
        /// </summary>
        public static string GSCheckText {
            get {
                return ResourceManager.GetString("GSCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Snooper check.
        /// </summary>
        public static string GSCheckTitle {
            get {
                return ResourceManager.GetString("GSCheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your nickname is already used by somebody on this server. You can choose another nickname in Settings..
        /// </summary>
        public static string GSNickInUseText {
            get {
                return ResourceManager.GetString("GSNickInUseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now known as {1}..
        /// </summary>
        public static string GSNicknameChange {
            get {
                return ResourceManager.GetString("GSNicknameChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected nickname is already in use!.
        /// </summary>
        public static string GSNicknameInUse {
            get {
                return ResourceManager.GetString("GSNicknameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has left the server ({0})..
        /// </summary>
        public static string GSQuitWMessage {
            get {
                return ResourceManager.GetString("GSQuitWMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has left the server..
        /// </summary>
        public static string GSQuitWOMessage {
            get {
                return ResourceManager.GetString("GSQuitWOMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Snooper is still running here..
        /// </summary>
        public static string GSRunningTaskbar {
            get {
                return ResourceManager.GetString("GSRunningTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No trolling please!.
        /// </summary>
        public static string GSVersionTrolling {
            get {
                return ResourceManager.GetString("GSVersionTrolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #worms.
        /// </summary>
        public static string GSWormsText {
            get {
                return ResourceManager.GetString("GSWormsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When your name appears in chat:.
        /// </summary>
        public static string HighlightSettingText {
            get {
                return ResourceManager.GetString("HighlightSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been highlighted in {0}!.
        /// </summary>
        public static string HightLightMessage {
            get {
                return ResourceManager.GetString("HightLightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host a game.
        /// </summary>
        public static string HostAGameText {
            get {
                return ResourceManager.GetString("HostAGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoster.exe does not exist! You can not host without that file!.
        /// </summary>
        public static string HosterExeText {
            get {
                return ResourceManager.GetString("HosterExeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to host a game. Probably you have hosted too many games recently. Please wait a while!.
        /// </summary>
        public static string HostFailText {
            get {
                return ResourceManager.GetString("HostFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send hosting action to channel?.
        /// </summary>
        public static string HostingAction {
            get {
                return ResourceManager.GetString("HostingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (optional):.
        /// </summary>
        public static string HostingPasswordLabel {
            get {
                return ResourceManager.GetString("HostingPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host a game.
        /// </summary>
        public static string HostingTitle {
            get {
                return ResourceManager.GetString("HostingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style of hyperlinks:.
        /// </summary>
        public static string HyperlinksStyleText {
            get {
                return ResourceManager.GetString("HyperlinksStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore list.
        /// </summary>
        public static string IgnoreListTitle {
            get {
                return ResourceManager.GetString("IgnoreListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoHeaderLabel {
            get {
                return ResourceManager.GetString("InfoHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InformationText {
            get {
                return ResourceManager.GetString("InformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info: {0}.
        /// </summary>
        public static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In game names.
        /// </summary>
        public static string InGameNamesLabel {
            get {
                return ResourceManager.GetString("InGameNamesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In hoster names.
        /// </summary>
        public static string InHosterNamesLabel {
            get {
                return ResourceManager.GetString("InHosterNamesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In join messages.
        /// </summary>
        public static string InJoinMessagesLabel {
            get {
                return ResourceManager.GetString("InJoinMessagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In messages.
        /// </summary>
        public static string InMessagesLabel {
            get {
                return ResourceManager.GetString("InMessagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In sender names.
        /// </summary>
        public static string InSenderNamesLabel {
            get {
                return ResourceManager.GetString("InSenderNamesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        public static string InvalidValueText {
            get {
                return ResourceManager.GetString("InvalidValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic:.
        /// </summary>
        public static string ItalicLabel {
            get {
                return ResourceManager.GetString("ItalicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join and close snooper.
        /// </summary>
        public static string JoinCloseText {
            get {
                return ResourceManager.GetString("JoinCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join this game.
        /// </summary>
        public static string JoinGameText {
            get {
                return ResourceManager.GetString("JoinGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to joined the channel..
        /// </summary>
        public static string JoinMessage {
            get {
                return ResourceManager.GetString("JoinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join message style:.
        /// </summary>
        public static string JoinMessageStyleText {
            get {
                return ResourceManager.GetString("JoinMessageStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kicked by {0}.
        /// </summary>
        public static string KickMessage {
            get {
                return ResourceManager.GetString("KickMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart Great Snooper to apply new language settings everywhere!.
        /// </summary>
        public static string LanguageChangedText {
            get {
                return ResourceManager.GetString("LanguageChangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEnName {
            get {
                return ResourceManager.GetString("LanguageEnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .. and without this nice community ;).
        /// </summary>
        public static string LastLineText {
            get {
                return ResourceManager.GetString("LastLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the snooper stops searching league game:.
        /// </summary>
        public static string LeagueFailSettingText {
            get {
                return ResourceManager.GetString("LeagueFailSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League Game Searcher.
        /// </summary>
        public static string LeagueGameTitle {
            get {
                return ResourceManager.GetString("LeagueGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League players.
        /// </summary>
        public static string LeaguePlayersGroupText {
            get {
                return ResourceManager.GetString("LeaguePlayersGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to turn off league searcher?.
        /// </summary>
        public static string LeagueSearcherRunningText {
            get {
                return ResourceManager.GetString("LeagueSearcherRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for league game.
        /// </summary>
        public static string LeagueSearcherTooltip {
            get {
                return ResourceManager.GetString("LeagueSearcherTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leagues may be still loading, please wait!.
        /// </summary>
        public static string LeaguesLoadingText {
            get {
                return ResourceManager.GetString("LeaguesLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the snooper finds a league game:.
        /// </summary>
        public static string LeagueSoundSettingText {
            get {
                return ResourceManager.GetString("LeagueSoundSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave this channel.
        /// </summary>
        public static string LeaveChannelText {
            get {
                return ResourceManager.GetString("LeaveChannelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License: GPLv2.
        /// </summary>
        public static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add item to the list enter text into the textbox and press enter. To remove item from the list right click on an item and choose remove..
        /// </summary>
        public static string ListEditorInfoText {
            get {
                return ResourceManager.GetString("ListEditorInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ListEditorInfoTitle {
            get {
                return ResourceManager.GetString("ListEditorInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogInText {
            get {
                return ResourceManager.GetString("LogInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOutText {
            get {
                return ResourceManager.GetString("LogOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program was written by Tomi.
        /// </summary>
        public static string MadeByText {
            get {
                return ResourceManager.GetString("MadeByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark me away when I host or join a game:.
        /// </summary>
        public static string MarkAwayText {
            get {
                return ResourceManager.GetString("MarkAwayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Color:.
        /// </summary>
        public static string MessageColorLabel {
            get {
                return ResourceManager.GetString("MessageColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send action message to the channel if I join a game:.
        /// </summary>
        public static string MessageJoinedGameText {
            get {
                return ResourceManager.GetString("MessageJoinedGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        public static string MessageLabel {
            get {
                return ResourceManager.GetString("MessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message logs.
        /// </summary>
        public static string MessageLogsText {
            get {
                return ResourceManager.GetString("MessageLogsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string MessagesText {
            get {
                return ResourceManager.GetString("MessagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style of message arrived time:.
        /// </summary>
        public static string MessageTimeStyleText {
            get {
                return ResourceManager.GetString("MessageTimeStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the time when the message arrived:.
        /// </summary>
        public static string MessageTimeText {
            get {
                return ResourceManager.GetString("MessageTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing value.
        /// </summary>
        public static string MissingValueText {
            get {
                return ResourceManager.GetString("MissingValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info.
        /// </summary>
        public static string MoreInfoText {
            get {
                return ResourceManager.GetString("MoreInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds on / off.
        /// </summary>
        public static string MuteTooltip {
            get {
                return ResourceManager.GetString("MuteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string NewsWindowTitle {
            get {
                return ResourceManager.GetString("NewsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new update available for Great Snooper! Would you like to download it now?.
        /// </summary>
        public static string NewVersionText {
            get {
                return ResourceManager.GetString("NewVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick Color:.
        /// </summary>
        public static string NickColorLabel {
            get {
                return ResourceManager.GetString("NickColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your nickname!.
        /// </summary>
        public static string NickEmptyText {
            get {
                return ResourceManager.GetString("NickEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your nickname contains one or more forbidden characters! Use characters from the English alphabet, numbers, - or `!.
        /// </summary>
        public static string NickHasBadChar {
            get {
                return ResourceManager.GetString("NickHasBadChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick.
        /// </summary>
        public static string NickHeaderLabel {
            get {
                return ResourceManager.GetString("NickHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This nickname is already in use! Please choose an other one! Note: if you lost your internet connection, you may need to wait 1 or 2 minutes until the server releases your broken nickname..
        /// </summary>
        public static string NicknameInUseText {
            get {
                return ResourceManager.GetString("NicknameInUseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname:.
        /// </summary>
        public static string NicknameText {
            get {
                return ResourceManager.GetString("NicknameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your nickname should begin with a character from the English aplhabet or with ` character!.
        /// </summary>
        public static string NickStartsBad {
            get {
                return ResourceManager.GetString("NickStartsBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No group.
        /// </summary>
        public static string NoGroupText {
            get {
                return ResourceManager.GetString("NoGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the league(s) you are looking for!.
        /// </summary>
        public static string NoLeaguesSelectedError {
            get {
                return ResourceManager.GetString("NoLeaguesSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice message style:.
        /// </summary>
        public static string NoticeMessageStyleText {
            get {
                return ResourceManager.GetString("NoticeMessageStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NotificationsText {
            get {
                return ResourceManager.GetString("NotificationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is hosting a game: {1}.
        /// </summary>
        public static string NotificatorGameText {
            get {
                return ResourceManager.GetString("NotificatorGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to turn off notificator?.
        /// </summary>
        public static string NotificatorRunningText {
            get {
                return ResourceManager.GetString("NotificatorRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificator.
        /// </summary>
        public static string NotificatorTooltip {
            get {
                return ResourceManager.GetString("NotificatorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} joined {1}!.
        /// </summary>
        public static string NotifOnlineMessage {
            get {
                return ResourceManager.GetString("NotifOnlineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the notificator finds something:.
        /// </summary>
        public static string NotifSoundSettingText {
            get {
                return ResourceManager.GetString("NotifSoundSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently offline..
        /// </summary>
        public static string OfflineMessage {
            get {
                return ResourceManager.GetString("OfflineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKText {
            get {
                return ResourceManager.GetString("OKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is online..
        /// </summary>
        public static string OnlineMessage {
            get {
                return ResourceManager.GetString("OnlineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other 1.
        /// </summary>
        public static string Other1GroupText {
            get {
                return ResourceManager.GetString("Other1GroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other 2.
        /// </summary>
        public static string Other2GroupText {
            get {
                return ResourceManager.GetString("Other2GroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other 3.
        /// </summary>
        public static string Other3GroupText {
            get {
                return ResourceManager.GetString("Other3GroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other 4.
        /// </summary>
        public static string Other4GroupText {
            get {
                return ResourceManager.GetString("Other4GroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has left the channel..
        /// </summary>
        public static string PartMessage {
            get {
                return ResourceManager.GetString("PartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has left the channel ({0})..
        /// </summary>
        public static string PartMessage2 {
            get {
                return ResourceManager.GetString("PartMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part message style:.
        /// </summary>
        public static string PartMessageStyleText {
            get {
                return ResourceManager.GetString("PartMessageStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player:.
        /// </summary>
        public static string PlayerLabel {
            get {
                return ResourceManager.GetString("PlayerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player list.
        /// </summary>
        public static string PlayersText {
            get {
                return ResourceManager.GetString("PlayersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private message arrived:.
        /// </summary>
        public static string PMBeepSettingText {
            get {
                return ResourceManager.GetString("PMBeepSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is online..
        /// </summary>
        public static string PMOnlineMessage {
            get {
                return ResourceManager.GetString("PMOnlineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There may be messages that this user could not receive!.
        /// </summary>
        public static string PMPingTimeoutMessage {
            get {
                return ResourceManager.GetString("PMPingTimeoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string QuestionText {
            get {
                return ResourceManager.GetString("QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit message style:.
        /// </summary>
        public static string QuitMessageStyleText {
            get {
                return ResourceManager.GetString("QuitMessageStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit message:.
        /// </summary>
        public static string QuitMessageText {
            get {
                return ResourceManager.GetString("QuitMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string RankHeaderLabel {
            get {
                return ResourceManager.GetString("RankHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank:.
        /// </summary>
        public static string RankText {
            get {
                return ResourceManager.GetString("RankText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Snooper has reconnected..
        /// </summary>
        public static string ReconnectMessage {
            get {
                return ResourceManager.GetString("ReconnectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh game list.
        /// </summary>
        public static string RefrestGameListText {
            get {
                return ResourceManager.GetString("RefrestGameListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from conversation.
        /// </summary>
        public static string RemoveFromConvText {
            get {
                return ResourceManager.GetString("RemoveFromConvText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from ignore list.
        /// </summary>
        public static string RemoveIgnoreText {
            get {
                return ResourceManager.GetString("RemoveIgnoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveText {
            get {
                return ResourceManager.GetString("RemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send back message in private chats if I am back:.
        /// </summary>
        public static string SendBackText {
            get {
                return ResourceManager.GetString("SendBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        public static string ServerErrorMessage {
            get {
                return ResourceManager.GetString("ServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The official server is: wormnet1.team17.com, you can find there all the players. But sometimes it is not accessable due to maintenance. Then you can use an alternative server to play for that short time..
        /// </summary>
        public static string ServerInfoText {
            get {
                return ResourceManager.GetString("ServerInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About servers.
        /// </summary>
        public static string ServerInfoTitle {
            get {
                return ResourceManager.GetString("ServerInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string ServerListEditorTitle {
            get {
                return ResourceManager.GetString("ServerListEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a server!.
        /// </summary>
        public static string ServerMissingText {
            get {
                return ResourceManager.GetString("ServerMissingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server disconnected: {0}.
        /// </summary>
        public static string ServerQuitMessage {
            get {
                return ResourceManager.GetString("ServerQuitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string ServerText {
            get {
                return ResourceManager.GetString("ServerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show messages of banned users in the channels:.
        /// </summary>
        public static string ShowBannedMessagesText {
            get {
                return ResourceManager.GetString("ShowBannedMessagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show banned users in user list:.
        /// </summary>
        public static string ShowBannedUsersText {
            get {
                return ResourceManager.GetString("ShowBannedUsersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show information column in user list:.
        /// </summary>
        public static string ShowInfoColumnText {
            get {
                return ResourceManager.GetString("ShowInfoColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show news.
        /// </summary>
        public static string ShowNewsText {
            get {
                return ResourceManager.GetString("ShowNewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show snooper.
        /// </summary>
        public static string ShowSnooperText {
            get {
                return ResourceManager.GetString("ShowSnooperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show #worms channel:.
        /// </summary>
        public static string ShowWormsText {
            get {
                return ResourceManager.GetString("ShowWormsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent join and close snooper.
        /// </summary>
        public static string SilentJoinCloseText {
            get {
                return ResourceManager.GetString("SilentJoinCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent join.
        /// </summary>
        public static string SilentJoinText {
            get {
                return ResourceManager.GetString("SilentJoinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple login.
        /// </summary>
        public static string SimpleLoginText {
            get {
                return ResourceManager.GetString("SimpleLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string SizeLabel {
            get {
                return ResourceManager.GetString("SizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string SoundsText {
            get {
                return ResourceManager.GetString("SoundsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam the channel?.
        /// </summary>
        public static string SpamChannelText {
            get {
                return ResourceManager.GetString("SpamChannelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Snooper stopped spamming and searching for league game(s)!.
        /// </summary>
        public static string SpamStopMessage {
            get {
                return ResourceManager.GetString("SpamStopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start notificator with snooper.
        /// </summary>
        public static string StartNotifWithSnooper {
            get {
                return ResourceManager.GetString("StartNotifWithSnooper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start searching.
        /// </summary>
        public static string StartSearchingText {
            get {
                return ResourceManager.GetString("StartSearchingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run WA.exe.
        /// </summary>
        public static string StartWAExeTooltip1 {
            get {
                return ResourceManager.GetString("StartWAExeTooltip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run alternative WA.exe.
        /// </summary>
        public static string StartWAExeTooltip2 {
            get {
                return ResourceManager.GetString("StartWAExeTooltip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop searching.
        /// </summary>
        public static string StopSearchingText {
            get {
                return ResourceManager.GetString("StopSearchingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough:.
        /// </summary>
        public static string StrikethroughLabel {
            get {
                return ResourceManager.GetString("StrikethroughLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System message style:.
        /// </summary>
        public static string SystemMessageStyleText {
            get {
                return ResourceManager.GetString("SystemMessageStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string SystemUserName {
            get {
                return ResourceManager.GetString("SystemUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program would never exist without the help of:.
        /// </summary>
        public static string ThanksText {
            get {
                return ResourceManager.GetString("ThanksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string ThemeText {
            get {
                return ResourceManager.GetString("ThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has changed the topic of the channel to &quot;{1}&quot;..
        /// </summary>
        public static string TopicMessage {
            get {
                return ResourceManager.GetString("TopicMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable tray flashing:.
        /// </summary>
        public static string TrayFlashingText {
            get {
                return ResourceManager.GetString("TrayFlashingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable tray balloon messages:.
        /// </summary>
        public static string TrayNotificationsText {
            get {
                return ResourceManager.GetString("TrayNotificationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzer.
        /// </summary>
        public static string TusAnalyzerText {
            get {
                return ResourceManager.GetString("TusAnalyzerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given username or password was incorrent!.
        /// </summary>
        public static string TusAuthFailText {
            get {
                return ResourceManager.GetString("TusAuthFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The communication with tus-wa.com has failed. Please try again!.
        /// </summary>
        public static string TusCommFailText {
            get {
                return ResourceManager.GetString("TusCommFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaints forum.
        /// </summary>
        public static string TusComplaintsText {
            get {
                return ResourceManager.GetString("TusComplaintsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cups.
        /// </summary>
        public static string TusCupsText {
            get {
                return ResourceManager.GetString("TusCupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Snooper topic.
        /// </summary>
        public static string TusGSTopicText {
            get {
                return ResourceManager.GetString("TusGSTopicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string TusHomePageText {
            get {
                return ResourceManager.GetString("TusHomePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occoured! Please try again!.
        /// </summary>
        public static string TusLoginFailText {
            get {
                return ResourceManager.GetString("TusLoginFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string TusLoginFailTitle {
            get {
                return ResourceManager.GetString("TusLoginFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUS login.
        /// </summary>
        public static string TusLoginText {
            get {
                return ResourceManager.GetString("TusLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your TUS nickname!.
        /// </summary>
        public static string TusNickEmptyText {
            get {
                return ResourceManager.GetString("TusNickEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUS nickname:.
        /// </summary>
        public static string TusNicknameText {
            get {
                return ResourceManager.GetString("TusNicknameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your TUS password!.
        /// </summary>
        public static string TusPasswordEmptyText {
            get {
                return ResourceManager.GetString("TusPasswordEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUS password:.
        /// </summary>
        public static string TusPasswordText {
            get {
                return ResourceManager.GetString("TusPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private messages.
        /// </summary>
        public static string TusPmsText {
            get {
                return ResourceManager.GetString("TusPmsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent games.
        /// </summary>
        public static string TusRecentGamesText {
            get {
                return ResourceManager.GetString("TusRecentGamesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report page.
        /// </summary>
        public static string TusReportText {
            get {
                return ResourceManager.GetString("TusReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standings.
        /// </summary>
        public static string TusStandingsText {
            get {
                return ResourceManager.GetString("TusStandingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournaments.
        /// </summary>
        public static string TusTournamentsText {
            get {
                return ResourceManager.GetString("TusTournamentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline:.
        /// </summary>
        public static string UnderlineLabel {
            get {
                return ResourceManager.GetString("UnderlineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start the updater! Please try to run it manually from the installation directory of Great Snooper!.
        /// </summary>
        public static string UpdaterFailText {
            get {
                return ResourceManager.GetString("UpdaterFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User groups.
        /// </summary>
        public static string UserGroupsText {
            get {
                return ResourceManager.GetString("UserGroupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style of your message:.
        /// </summary>
        public static string UserMessageStyleText {
            get {
                return ResourceManager.GetString("UserMessageStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersText {
            get {
                return ResourceManager.GetString("UsersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using WormNat2?.
        /// </summary>
        public static string UsingWormNat2 {
            get {
                return ResourceManager.GetString("UsingWormNat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0}&apos;s profile.
        /// </summary>
        public static string ViewTusText {
            get {
                return ResourceManager.GetString("ViewTusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string VolumeTooltip {
            get {
                return ResourceManager.GetString("VolumeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WA.exe is missing. Please set WA.exe in the Settings!.
        /// </summary>
        public static string WAExeMissingText {
            get {
                return ResourceManager.GetString("WAExeMissingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WA.exe can not be found! Please set WA.exe in the Settings!.
        /// </summary>
        public static string WAExeNotExistsText {
            get {
                return ResourceManager.GetString("WAExeNotExistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops, it seems like Great Snooper could not find your WA.exe! You can not host or join a game without that file. Would you like to locate your WA.exe now? You can do it later in the settings too..
        /// </summary>
        public static string WAExeNotFoundText {
            get {
                return ResourceManager.GetString("WAExeNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WA.exe:.
        /// </summary>
        public static string WAExeText {
            get {
                return ResourceManager.GetString("WAExeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative WA.exe:.
        /// </summary>
        public static string WAExeText2 {
            get {
                return ResourceManager.GetString("WAExeText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set W:A task priority to high:.
        /// </summary>
        public static string WaHighPriorityText {
            get {
                return ResourceManager.GetString("WaHighPriorityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already in a game!.
        /// </summary>
        public static string WAIsRunningText {
            get {
                return ResourceManager.GetString("WAIsRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Great Snooper!.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}!.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is TUS login?.
        /// </summary>
        public static string WhatIsTusLoginLabel {
            get {
                return ResourceManager.GetString("WhatIsTusLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUS is The Ultimate Site. It is a website for Worms: Armageddon, which has a lot of things for the game, such as: leagues, cups, tournaments, schemes, maps, forum, etc. It also supports snoopers. If you login with your TUS account into the snooper, then your rank will be your TUS league rank, your clan will also be set and you will be marked online on the website. . You can also set a different nickname and a password for snooper login on TUS site in your Account Settings..
        /// </summary>
        public static string WhatIsTusLoginText {
            get {
                return ResourceManager.GetString("WhatIsTusLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string WindowText {
            get {
                return ResourceManager.GetString("WindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the server! Check if the server address is correct or try again later (probably maintenance time)!.
        /// </summary>
        public static string WNCommFailText {
            get {
                return ResourceManager.GetString("WNCommFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has left WormNet ({0})..
        /// </summary>
        public static string WNQuitWMessage {
            get {
                return ResourceManager.GetString("WNQuitWMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has left WormNet..
        /// </summary>
        public static string WNQuitWOMessage {
            get {
                return ResourceManager.GetString("WNQuitWOMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greetings WormNAT2 user! This is a reminder message to remind you that WormNAT2 is a free service. Using WormNAT2 tunnels all data through a proxy server hosted by the community, thus consuming bandwidth and other resources. Therefore, we would like to ask you to only use WormNAT2 when you have already tried configuring hosting the proper way. Don&apos;t forget that you can find instructions on how to set up hosting here: http://worms2d.info/Hosting.
        /// </summary>
        public static string WormNat2GreetingText {
            get {
                return ResourceManager.GetString("WormNat2GreetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #worms channel nickname:.
        /// </summary>
        public static string WormsNickLabel {
            get {
                return ResourceManager.GetString("WormsNickLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
